import React from 'react'
import Multiple_Inputs from "../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Form_Handing_22-07-2026/Multiple_Inputs";
import Add_Remove_Input from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Form_Handing_22-07-2026/Add_Remove_Input';
import Student_Form from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Form_Handing_22-07-2026/Student_Form';
import Checkbox_Form from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Form_Handing_22-07-2026/Checkbox_Form';
import Form_Array from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Form_Handing_22-07-2026/Form_Array';
import Textarea from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Controlled_Component_22-07-2026/Textarea';
import Dropdown from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Controlled_Component_22-07-2026/Dropdown';
import RadioButton from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Controlled_Component_22-07-2026/RadioButton';
import Login_Form from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Controlled_Component_22-07-2026/Login_Form';
import Student_Input_Form from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Handle_Input_Fields_22-07-2026/Student_Input_Form';
import File_Input from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Controlled_Component_22-07-2026/File_Input';
import Registration from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Registration_Form_22-07-2026/Registration';
import Error_Form from '../../components_07-07-2026/Dynamic_Form_Handling_22-07-2026/Error_Handling_22-07-2026/Error_Form';

function Form_Handling_page() {
  return (
    <>
    <Multiple_Inputs/>
    <hr/>
    <Add_Remove_Input/>
    <hr/>
    <br/>
    <h2 className='font-bold'>student form</h2>
    <Student_Form/>
    <hr/>
    <h2 className='font-bold'>checkbox</h2>
    <Checkbox_Form/>
    <hr/>
    <h2 className='font-bold'>Dynamic Form generated by array </h2>
    <Form_Array/>
    <hr/>
    <br/>
    <Textarea/>
    <hr/>
    <br/>
    <Dropdown/>
    <hr/>
    <br/>
    <h2 className='font-bold'>Radio Button</h2>
    <RadioButton/>
    <hr/>
    <br/>
    <h1 className='font-bold'>Login Form</h1>
    <Login_Form/>
    <hr/>
    <br/>
    <h1 className='font-bold'>Student Form</h1>
    <Student_Input_Form/>

    <hr/>
    <br/>
    <h1 className='font-bold'>Input file</h1>

    <File_Input/>
    <hr/>
    <hr/>
    <br/><br/>
    <h1 className='font-bold'>Registration form</h1><br/>
    <Registration/>

    <hr/>
    <br/>
    <h2 className='font-bold'>error handling</h2>
    <Error_Form/>

    </>
  )
}

export default Form_Handling_page